import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import PageTitle from "~/components/UI/pageTitle/pageTitle";
import { createDocumentHead } from "~/utils/createDocumentHead";

export default component$(() => {
  return (
    <main>
      <div class="relative mx-auto max-w-screen-lg px-4 py-4 md:py-10">
        <article
          class="mt-8 w-full min-w-0 max-w-6xl px-1 md:px-6"
          style="min-height: calc(100vh - 103px);"
        >
          <div class="prose prose-vercel max-w-none">
            <PageTitle chapterNumber={0} chapterTitle="Privacy Policy" />
            <p>
              Welcome to our Privacy Policy page! At Learn Qwik, we are
              committed to protecting your privacy and ensuring that your
              personal data is handled safely and responsibly. This policy
              outlines our practices regarding the collection, use, and
              protection of your information.
            </p>
            <h2>Definitions</h2>
            <p>
              <b>Client:</b> any professional or capable individual according to
              articles 1123 and subsequent of the Civil Code, or legal entity,
              who visits the Website subject to these general conditions.
              <br />
              <b>Services and Benefits:</b>{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              provides the Clients:
            </p>
            <p>
              <b>Content:</b> All the elements constituting the information
              present on the Site, including texts – images – videos.
            </p>
            <p>
              <b>Client Information:</b> Hereinafter referred to as
              "Information(s)" which correspond to all the personal data that
              may be held by{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              for managing your account, customer relations management, and for
              analysis and statistics purposes.
            </p>
            <p>
              <b>User:</b> Internet user connecting, using the aforementioned
              site.
            </p>
            <p>
              <b>Personal Information:</b> “The information that allows, in any
              form whatsoever, directly or indirectly, the identification of the
              natural persons to whom it applies” (Article 4 of Law No. 78-17 of
              January 6, 1978).
            </p>
            <p>
              The terms "personal data", "data subject", "processor", and
              "sensitive data" have the meanings defined by the General Data
              Protection Regulation (GDPR: No. 2016-679)
            </p>
            <h2>How We Use Your Information</h2>
            <p>
              This section of our Privacy Policy explains how we use the
              information we collect from you when you use our services. We take
              your privacy seriously and only process your personal data in
              accordance with this policy.
            </p>
            <h2>1. Presentation of the website.</h2>
            <p>
              Under Article 6 of Law No. 2004-575 of June 21, 2004 for
              confidence in the digital economy, it is specified to the users of
              the website{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              the identity of the various parties involved in its creation and
              its follow-up:
            </p>
            <p>
              <strong>Owner:</strong> EI LaReponseDev – 1 Rue Denis Magdelon
              13009 Marseille
              <br />
              <strong>Publication Manager:</strong> Loic Giuliano –
              lareponsedev2023@outlook.fr
              <br />
              The publication manager is either a natural person or a legal
              entity.
              <br />
              <strong>Webmaster:</strong> Loic Giuliano –
              contact@lareponsedev.com
              <br />
              <strong>Host:</strong> Vercel – Vercel Inc. – 340 S Lemon Ave
              #4133 CA 91789 Walnut https://vercel.com
              <br />
              <strong>Data Protection Officer:</strong> Loic Giuliano –
              lareponsedev2023@outlook.fr
              <br />
            </p>
            <div ng-bind-html="linkHTML">
              <p>
                This legal notice is generated by the{" "}
                <a
                  href="https://fr.orson.io/1371/generateur-mentions-legales"
                  title="GDPR legal notice generator"
                >
                  GDPR legal notice generator by Orson.io
                </a>
              </p>
            </div>
            <h2>
              2. General conditions of use of the site and the services offered.
            </h2>
            <p>
              The Site constitutes a work of the spirit protected by the
              provisions of the Intellectual Property Code and applicable
              International Regulations. The Client may in no way reuse,
              transfer or exploit for their own account any or all of the
              elements or works of the Site.
            </p>
            <p>
              The use of the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              implies full and complete acceptance of the general conditions of
              use described below. These conditions of use may be modified or
              supplemented at any time, users of the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              are therefore invited to consult them regularly.
            </p>
            <p>
              This website is normally accessible to users at all times.
              However, an interruption for technical maintenance may be decided
              by{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              , who will then endeavor to communicate to users the dates and
              times of the intervention. The website{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is updated regularly by{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              responsible. Similarly, the legal notices may be modified at any
              time: they nevertheless impose themselves on the user who is
              invited to refer to them as often as possible in order to take
              note of them.
            </p>
            <h2>3. Description of the services provided.</h2>
            <p>
              The website{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              aims to provide information concerning all the company's
              activities.
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              strives to provide on the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              as precise information as possible. However, it cannot be held
              responsible for omissions, inaccuracies and deficiencies in the
              update, whether by its own doing or by the third-party partners
              who provide this information.
            </p>
            <p>
              All information indicated on the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is given indicatively, and is likely to evolve. Moreover, the
              information on the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is not exhaustive. It is given subject to modifications having
              been made since it was put online.
            </p>
            <h2>4. Contractual limitations on technical data.</h2>
            <p>
              The site uses JavaScript technology. The website cannot be held
              responsible for material damages related to the use of the site.
              Furthermore, the user of the site agrees to access the site using
              recent equipment, not containing any viruses and with an
              up-to-date latest generation browser The site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is hosted by a provider in the territory of the European Union in
              accordance with the provisions of the General Data Protection
              Regulation (GDPR: No. 2016-679)
            </p>
            <p>
              The aim is to provide a service that ensures the best
              accessibility rate. The host ensures the continuity of its service
              24 hours a day, every day of the year. It reserves the right,
              however, to interrupt the hosting service for the shortest
              possible duration, notably for maintenance, improvement of its
              infrastructures, failure of its infrastructures, or if the
              Services and Benefits generate deemed abnormal traffic.
            </p>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              and the host cannot be held responsible in case of malfunction of
              the Internet network, telephone lines or computer and telephony
              equipment, notably related to the network congestion preventing
              access to the server.
            </p>
            <h2>5. Intellectual property and counterfeits.</h2>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              owns the intellectual property rights and holds the rights to use
              all the items accessible on the website, particularly the texts,
              images, graphics, logos, videos, icons and sounds. Any
              reproduction, representation, modification, publication,
              adaptation of all or part of the elements of the site, regardless
              of the means or process used, is prohibited, without prior written
              permission from:{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              .
            </p>
            <p>
              Any unauthorized use of the site or any of its elements will be
              considered as constituting an infringement and prosecuted in
              accordance with the provisions of articles L.335-2 and following
              of the Code of Intellectual Property.
            </p>
            <h2>6. Limitations of liability.</h2>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              acts as the publisher of the site.{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is responsible for the quality and truthfulness of the Content it
              publishes.
            </p>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              cannot be held liable for direct and indirect damage to the user's
              equipment when accessing the{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              website, and resulting either from the use of equipment that does
              not meet the specifications indicated in point 4, or the
              appearance of a bug or an incompatibility.
            </p>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              cannot also be held liable for indirect damages (such as a loss of
              market or loss of a chance) resulting from the use of the{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              site. Interactive spaces (possibility to ask questions in the
              contact area) are available to users.{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              reserves the right to remove, without prior notice, any content
              posted in this space that contravenes the legislation applicable
              in France, in particular the provisions relating to data
              protection. If necessary,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              also reserves the right to challenge the civil and/or criminal
              liability of the user, in particular in the case of a message of a
              racist, insulting, defamatory, or pornographic nature, whatever
              the medium used (text, photography…).
            </p>
            <h2>7. Management of personal data.</h2>
            <p>
              The Client is informed of regulations concerning marketing
              communication, the law of June 21, 2014 for the confidence in the
              Digital Economy, the Computer Law and Freedom of August 6, 2004 as
              well as the General Data Protection Regulation (GDPR: No.
              2016-679).
            </p>
            <h3>7.1 Data collection managers</h3>
            <p>
              For Personal Data collected as part of the creation of the User's
              personal account and his navigation on the Site, the manager of
              the processing of Personal Data is: LaReponseDev.{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              is represented by Loic Giuliano, its legal representative
            </p>
            <p>
              As the manager of the data it collects,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              undertakes to comply with the framework of the legal provisions in
              force. It is their responsibility in particular to establish the
              purposes of its data processing, to provide its prospects and
              customers, from the collection of their consents, complete
              information on the processing of their personal data and to
              maintain a processing register compliant with reality. Whenever{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              processes Personal Data,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              takes all reasonable measures to ensure the accuracy and relevance
              of the Personal Data with respect to the purposes for which{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              processes them.
            </p>
            <h3>7.2 Purpose of the data collected</h3>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              may process all or part of the data:
            </p>
            <ul>
              <li>
                to enable navigation on the Site and the management and
                traceability of services and services ordered by the user: login
                and usage data of the Site, billing, order history, etc.{" "}
              </li>

              <li>
                to prevent and fight against computer fraud (spamming,
                hacking...): computer equipment used for browsing, IP address,
                hashed password{" "}
              </li>

              <li>
                to improve navigation on the Site: connection and usage data{" "}
              </li>

              <li>
                to conduct optional satisfaction surveys on{" "}
                <a href="https://www.learn-qwik.com/">
                  https://www.learn-qwik.com/
                </a>
                : email address{" "}
              </li>
              <li>
                to carry out communication campaigns (sms, mail): phone number,
                email address
              </li>
            </ul>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              does not market your personal data which is therefore used only by
              necessity or for statistical and analysis purposes.
            </p>
            <h3>7.3 Access, rectification and opposition rights</h3>
            <p>
              In accordance with European regulations in force, Users of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              have the following rights:
            </p>
            <ul>
              <li>
                right of access (Article 15 GDPR) and rectification (Article 16
                GDPR), update, completeness of Users' data right of blocking or
                erasing personal data of Users (Article 17 of the GDPR), when
                they are inaccurate, incomplete, ambiguous, outdated, or whose
                collection, use, disclosure, or storage is prohibited
              </li>

              <li>
                right to withdraw consent at any time (Article 13-2c GDPR)
              </li>

              <li>
                right to limit the processing of Users' data (Article 18 GDPR)
              </li>

              <li>
                right to object to the processing of Users' data (Article 21
                GDPR)
              </li>

              <li>
                right to the portability of the data that the Users will have
                provided, when these data undergo automated processing based on
                their consent or on a contract (Article 20 GDPR)
              </li>

              <li>
                right to determine the fate of Users' data after their death and
                to choose to whom{" "}
                <a href="https://www.learn-qwik.com/">
                  https://www.learn-qwik.com/
                </a>{" "}
                should communicate (or not) his data to a third party they have
                previously designated
              </li>
            </ul>
            <p>
              As soon as{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is aware of the death of a User and in the absence of instructions
              from them,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              undertakes to destroy their data, unless their retention proves
              necessary for probative purposes or to meet a legal obligation.
            </p>
            <p>
              If the User wishes to know how{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              uses their Personal Data, ask to rectify them or oppose their
              processing, the User can contact{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              in writing at the following address:
            </p>
            LaReponseDev – DPO, Loic Giuliano
            <br />1 Rue Denis Magdelon 13009 Marseille.
            <p>
              In this case, the User must indicate the Personal Data that they
              would like{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              to correct, update or delete, by identifying themselves precisely
              with a copy of an identity document (identity card or passport).
            </p>
            <p>
              Requests to delete Personal Data will be subject to the
              obligations that are imposed on{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              by law, in particular in terms of preservation or archiving of
              documents. Finally, Users of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              can file a complaint with the supervisory authorities, and in
              particular the CNIL (https://www.cnil.fr/en/plaintes).
            </p>
            <h3>7.4 Non-communication of personal data</h3>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              forbids itself to process, host or transfer the Information
              collected on its Customers to a country located outside the
              European Union or recognized as "non-adequate" by the European
              Commission without informing the customer beforehand. For all
              that,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              remains free to choose its technical and commercial subcontractors
              provided they present the necessary guarantees according to the
              requirements of the General Data Protection Regulation (GDPR: No.
              2016-679).
            </p>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              undertakes to take all necessary precautions to preserve the
              security of the Information and in particular that it is not
              communicated to unauthorized persons. However, if an incident
              impacting the integrity or confidentiality of the Client's
              Information is brought to the knowledge of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              , it must inform the Client as soon as possible and communicate
              the corrective measures taken. Moreover{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              does not collect any "sensitive data".
            </p>
            <p>
              The Personal Data of the User may be processed by subsidiaries of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              and subcontractors (service providers), exclusively to achieve the
              purposes of this policy.
            </p>
            <p>
              Within the limits of their respective attributions and for the
              purposes mentioned above, the main people likely to have access to
              the data of Users of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              are mainly our customer service agents.
            </p>
            <div ng-bind-html="rgpdHTML"></div>
            <h2>8. Incident Notification</h2>
            <p>
              Regardless of the efforts made, no method of transmission over the
              Internet and no method of electronic storage is completely secure.
              We cannot therefore guarantee absolute security. If we were aware
              of a security breach, we would notify affected users so that they
              can take appropriate measures. Our incident notification
              procedures take into account our legal obligations, whether at the
              national or European level. We commit to fully informing our
              clients of all matters related to the security of their account
              and providing all the necessary information to help them meet
              their own regulatory reporting obligations.
            </p>
            <p>
              No personal information of the user of the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is published without the user's knowledge, exchanged, transferred,
              assigned or sold on any medium to third parties. Only the
              hypothesis of the acquisition of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              and its rights would allow the transmission of said information to
              the potential purchaser who would in turn be held to the same
              obligations of conservation and modification of data with respect
              to the user of the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              .
            </p>
            <h3>Security</h3>
            <p>
              To ensure the security and confidentiality of Personal Data and
              Health Data,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              uses networks protected by standard devices such as by firewall,
              pseudonymization, encryption and password.{" "}
            </p>
            <p>
              During the processing of Personal Data,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              takes all reasonable measures aimed at protecting them against any
              loss, misuse, unauthorized access, disclosure, alteration or
              destruction.
            </p>
            <h2>9. "Cookies" and internet tags</h2>
            <p>
              The site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              contains a number of hyperlinks to other sites, set up with the
              authorization of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              . However,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              does not have the possibility to check the content of the sites
              visited, and will not assume any responsibility for this fact.
            </p>
            Unless you decide to disable cookies, you agree that the site may
            use them. You can disable these cookies at any time and free of
            charge from the deactivation options that are offered to you and
            recalled below, knowing that this may reduce or prevent
            accessibility to all or part of the Services offered by the site.
            <p></p>
            <h3>9.1. "COOKIES"</h3>
            <p>
              A "cookie" is a small information file sent to the User's browser
              and stored within the User's terminal (e.g. computer, smartphone),
              (hereinafter "Cookies"). This file includes information such as
              the User's domain name, Internet access provider, operating
              system, and the date and time of access. Cookies can in no way
              damage the User's terminal.
            </p>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              may process information concerning the User's visit to the Site,
              such as the pages viewed, the searches carried out. This
              information allows{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              to improve the content of the Site, and the User's navigation.
            </p>
            <p>
              Cookies facilitate navigation and/or the provision of the services
              offered by the Site, the User may configure their browser to allow
              them to decide whether they wish to accept them so that Cookies
              can be stored in the terminal or, conversely, be rejected, either
              systematically or according to their issuer. The User may also
              configure their browser software so that the acceptance or refusal
              of Cookies is proposed to them punctually, before a Cookie is
              likely to be stored in their terminal.{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              informs the User that, in this case, it is possible that not all
              functions of their browser software will be available.
            </p>
            <p>
              If the User refuses the storage of Cookies in their terminal or
              browser, or if the User deletes those stored there, the User is
              informed that their navigation and experience on the Site may be
              limited. This could also be the case when{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              or one of its service providers cannot recognize, for technical
              compatibility purposes, the type of browser used by the terminal,
              the language and display settings or the country from which the
              terminal appears to be connected to the Internet.
            </p>
            <p>
              Where applicable,{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              declines all responsibility for the consequent poor functioning of
              the Site and possible services offered by{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              , resulting (i) from the refusal of Cookies by the User (ii) the
              impossibility for{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              to record or consult the Cookies necessary for their functioning
              due to the choice of the User. For the management of Cookies and
              User choices, the configuration of each browser is different. It
              is described in the browser's help menu, which will tell the User
              how to change their Cookie preferences.
            </p>
            <p>
              At any time, the User can choose to express and change their
              preferences regarding Cookies.{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              may also use the services of external service providers to help
              collect and process the information described in this section.
            </p>
            <p>
              Finally, by clicking on the icons dedicated to Twitter, Facebook,
              Linkedin, and Google Plus social networks appearing on the Site of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              or in its mobile application and if the User has agreed to the
              deposit of cookies by continuing their navigation on the Website
              or mobile application of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              , Twitter, Facebook, Linkedin, and Google Plus may also deposit
              cookies on your terminals (computer, tablet, mobile phone).
            </p>
            <p>
              These types of cookies are only deposited on your terminals if you
              consent to it, by continuing your navigation on the Website or
              mobile application of{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              . At any time, the User may nevertheless withdraw their consent to{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              depositing this type of cookies.
            </p>
            <h3>Article 9.2. INTERNET TAGS</h3>
            <p>
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              may occasionally use internet tags (also called "tags", or action
              tags, one-pixel GIFs, transparent GIFs, invisible GIFs and
              one-to-one GIFs) and deploy them through a web analytics partner
              who may be located (and thus store the corresponding information,
              including the User's IP address) in a foreign country.
            </p>
            <p>
              These tags are placed both in online advertisements allowing users
              to access the Site, and on the various pages of it.
            </p>
            <p>
              This technology allows{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              to evaluate the responses of visitors to the Site and the
              effectiveness of its actions (for example, the number of times a
              page is opened and the information consulted), as well as the use
              of this Site by the User.
            </p>
            <p>
              The external provider may possibly collect information about
              visitors to the Site and other websites using these tags, compile
              reports on the Site's activity for{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>
              , and provide other services relating to the use of it and the
              Internet.
            </p>
            <p></p>
            <h2>10. Applicable law and jurisdiction.</h2>
            <p>
              Any dispute related to the use of the site{" "}
              <a href="https://www.learn-qwik.com/">
                https://www.learn-qwik.com/
              </a>{" "}
              is subject to French law. Except in cases where the law does not
              permit it, exclusive jurisdiction is granted to the competent
              courts of Marseille
            </p>
            <h2>Summary of Our Privacy Policy</h2>
            <p>
              To summarize, our Privacy Policy ensures that your data is
              protected. We do not share your information with third parties
              without your consent, and we use your data only to improve our
              services and provide you with a better user experience.
            </p>
          </div>
        </article>
      </div>
    </main>
  );
});

export const head: DocumentHead = createDocumentHead(
  "Privacy Policy",
  "Learn how we protect your privacy and personal data on Learn Qwik. Read our complete privacy policy for more details.",
  "https://www.learn-qwik.com/metaDashboard.png",
  "https://www.learn-qwik.com/learn/dashboard-app/",
);
